db/index.js
server/api/tripRoutes.js

We were having a seeding issue when trying to npm run seed where User was undefined 
Fixed that issue by adding model prop back to db/index.js file in the module.exports and also added models property where I am importing the models in the api/tripRoutes.js file
I tested using thunder client everything seems good!

fixed seeding issue

---

seed.js
server/api/tripRoutes.js

We needed users to be able to get all trips they are associated with, all active trips and all completed trips
Lets users view all trips they are associated with, view all active and all completed trips 
I tested using thunder client

Fix get routes for trips

---

client/redux/users.js

cookie functions in user store

cookie functions

---

client/redux/users.js

- added the words export on the functions

export cookie functions

---

package.json

added build script

---

client/redux/taskReducer.js

move taskReducer into client folder

add taskReducer file to new client file

---

seed.js

added more seed data reseed

---

seed.js

-user seed update to have username

user Seed Update

---

client/components/CompletedTrips.js
client/components/SingleUser.js
client/redux/tripReducer.js
client/store.js

Need to let users view completed and active trips in user dashboard
Sets up redux store (reducer, action type, action creator, thunk) to get all trips from the backend
na

Render active past trips

---

client/redux/taskReducer.js
server/api/tasks.js

Changed:
Added:
- Frontend:
- UPDATE_TASK
- DELETE_TASK
- UPDATE_TASK_USER
- GET_TASKS
- Backend:
- Delete
- Create
- Update
- user_task routes (post, update, delete)

More task route

---

client/components/Root.js
client/components/SingleTrip.js
client/components/TripTasks.js
client/redux/taskReducer.js
seed.js

single trip view, start of itinerary, seed fix

single trip view 

---

client/components/Root.js
client/components/SingleUser.js
client/components/UpdateUserForm.js
client/redux/auth.js
client/redux/users.js
db/models/User.js
server/api/users.js

-functional update user form with required telephone and email format
-function delete button with console warning when pressed

User Update Form Component

---

client/components/ActiveTrips.js
client/components/CompletedTrips.js
package-lock.json

cards were rendering weirdly so I fixed them

fixed trip card rendering

---

client/components/ActiveTrips.js
client/components/CompletedTrips.js
client/redux/tripReducer.js

Allows user to navigate from user dashboard to trip dashboard by clicking view trip button and changes url path to the tripId from the trip that is clicked

View trip button

---

client/components/SingleTrip.js
client/components/TaskComponents/EditTaskModal.js
client/components/TaskComponents/TaskCard.js
client/components/TaskComponents/TaskList.js
client/components/TripTaskTodo.js
client/components/TripTasks.js

Changed:
- rm testTrip dummy data
- utilizing useParam to fetch single trip
- adding trip as prop to components
- using trip prop in components
Added:
- structure of trip task edit model

Edit task on trip

---

client/components/ActiveTrips.js
client/components/CompletedTrips.js
client/components/TripTaskTodo.js
client/redux/tripReducer.js
seed.js
server/api/tripRoutes.js

fixed sorted dates in active trips

fixed sorting of dates

---

client/components/TaskComponents/AddNewTaskModal.js
client/components/TripTaskTodo.js
client/redux/taskReducer.js
server/api/tasks.js

Changed:
- added conditional rendering of subtype
- added date-time picker
- rm dummy data
- added prop to triptasktodo -> modal
Added:
- modal success rendering
- success checking

Add new task

---

client/components/TaskComponents/TaskCard.js
client/components/TripTaskTodo.js

added alert-delete from user dash task list into trip dash task todo

Trip task delete

---

client/components/Navbar.js
client/components/SignupForm.js
client/components/TaskComponents/AllTasks/AllTasks.js
client/components/UpdateUserForm.js
public/index.css
server/auth/index.js

- added token to database when signing up
- update profile delete button added
- sign up required field on front end added
- modified error messages in the front end

Update user form

---

client/components/SignupForm.js
db/models/User.js

- added max min to password length
- altered error message for username and email

max and min length added to password

---

client/components/LoginForm.js
client/components/Navbar.js
client/components/Root.js
client/components/SignupForm.js
client/redux/auth.js

-login goes to users
-sign up goes to users 
-fixed navbar css bug

Transitions

---

client/components/TaskComponents/TaskCard.js

Changed:
- got rid of conditional fragment in avatar
Added:
- added status color to itinerary cards

added status color to itinerary cards

---

client/components/Navbar.js
client/components/Root.js
public/index.css

nav bar was duplicated but i fixed it

Fix nav bar

---

client/components/Navbar.js

added conditional rendering back

---

client/components/ActiveTrips.js
client/components/SingleTrip.js
client/components/TaskComponents/TaskCard.js
client/components/TripTaskTodo.js
client/components/TripTasks.js
client/store.js

This is only for single trip view
Owners can delete a task, edit a trip, and add a new task
Owner cannot edit tasks or mark as complete
Attendee can ONLY view tasks and other trip info
Editors can edit tasks, delete tasks, mark as complete and add a new task
Editors cannot edit trip

Conditional rendering for role

---

client/components/ActiveTrips.js
client/components/Carousel.js
client/components/CompletedTrips.js
client/redux/tripReducer.js
server/api/tripRoutes.js

in user dashboard users can view their role in a trip and delete button should only show up if user is owner of that trip

Conditional render for userdashboard

---

client/components/TaskComponents/AddNewTaskModal.js
client/redux/taskReducer.js
db/models/Task.js

added form validation and alert

Add new task modal success

---

client/components/SingleTrip.js
client/components/TaskComponents/AddNewTaskModal.js
client/components/TaskComponents/EditTaskModal.js
client/components/TaskComponents/TaskCard.js
client/components/TripTaskTodo.js
seed.js

Added:
- setTimeout on task update success validation on EditTaskModal
- error msgs on addNewTaskMdoal and editTaskModal

Edit task form submit

---

client/components/TaskComponents/AllTasks/EditTaskAttendees.js
client/redux/taskReducer.js
server/api/tasks.js

- working update attendees
- sorry late notes!!!

working update attendees

---

client/components/TaskComponents/AllTasks/CompletedTaskCard.js
client/components/TaskComponents/AllTasks/TaskModal.js
client/redux/taskReducer.js
server/api/tasks.js

Debug task routes

---

client/components/TaskComponents/EditTaskAttendeesTripView.js
client/components/TaskComponents/EditTaskModal.js
client/components/TaskComponents/TaskCard.js
client/redux/taskReducer.js
server/api/gatekeepingmiddleware.js
server/api/tasks.js

Changed:
- task-user routes above task routes
- added tripId where needed in dispatches to thunks that send to gatekept routes
- changed tripId variable name that conflicted with TripId var needed for gatekeeping/desctructing
- fix form state repopulation
- added word break to card titles
- add use raw to isEditorOfTaskOrTripOwner (it could not ready _____.role w/o it)
- changed updateTask reducer case to replaced task in place instead of filter and re add
- rm some console logs
Added:
- added EditTaskAttendeesTrip View modal to cards

Fix gatekeeping button issues

---

client/components/Attendees/Searchbar.js
client/redux/tripReducer.js
server/api/tripRoutes.js
server/api/userTrips.js

fixed delete trip from user dashboard

---

client/components/TaskComponents/AllTasks/AllTasks.js
client/components/TaskComponents/AllTasks/TaskModal.js
client/components/TaskComponents/AllTasks/TasksCompleted.js
client/components/TaskComponents/AllTasks/TasksInProgress.js
client/components/UpdateUserForm.js
client/redux/users.js

- font changes
- toasts
- change of task name
- added info to edit page of task

Small updates

---

client/components/Attendees/TripAttendees.js
client/redux/tripReducer.js
server/api/userTrips.js

Adding a user to trip, editing users role on trip, and deleting user from trip work with gatekeeping middleware now!
Trip owner and trip editor can do this!

Fix gatekeep user trips

---

client/components/TaskComponents/AllTasks/EditTaskAttendees.js
client/components/TaskComponents/AllTasks/TaskModal.js
seed.js

- added validation for isOwner
- added validation for person is editor or owner of trip to be editor or owner of task

Routesdebug

---

client/components/Root.js

redirect to main

---

client/components/TaskComponents/AllTasks/EditTaskAttendees.js

filtering only trip memebers

---

client/components/TaskComponents/EditTaskModal.js

Added:
- task title form field
- title validation (cannot be blank)
- task title error

added provider_name editing

---

client/components/Attendees/Searchbar.js

Don't approve until after beta testing!

Feature: searchbar only displays members not on trip when adding

---

client/components/ActiveTrips.js
client/components/TaskComponents/AllTasks/EditTaskAttendees.js
client/redux/taskReducer.js
client/redux/tripReducer.js
package-lock.json
package.json
public/index.css
server/api/gatekeepingmiddleware.js
server/api/mail.js
server/api/tasks.js

added gatekeeping middleware to user task routes

user tasks gatekeeping 

---

client/components/TaskComponents/AddNewTaskModal.js
client/components/TaskComponents/EditTaskModal.js
client/components/TripTaskTodo.js

Changed:
- tasks section name to Task Planning Checklist
- edit trip and add new trip form labels for due date, start date, and end date,
- added blurb to add new task form
Added:
- info icon with popover explanation of how to use the Task Planning Checklist

Task renaming

---

client/components/SingleUser.js
client/components/TaskComponents/AllTasks/AllTasks.js
client/components/TaskComponents/AllTasks/CompletedTaskCard.js
client/components/TaskComponents/AllTasks/EditTaskAttendees.js
client/components/TaskComponents/AllTasks/TaskModal.js
client/components/TaskComponents/AllTasks/TasksCompleted.js
client/components/TaskComponents/AllTasks/TasksInProgress.js

- fixed owner view for completed tasks
- added extra filter of tasks to only render "active" tasks
- you can now only search for people who are part of the trip to add to task

Debug attendee

---

client/components/TaskComponents/AllTasks/CompletedTaskCard.js
client/components/TaskComponents/AllTasks/TaskModal.js
client/components/UpdateUserForm.js

delete buttons changed to flex

---

client/components/TaskComponents/AllTasks/AllTasks.js

fixed name error on task

---

seed.js

- checked seed
- added demo task descriptions

seeds all checked to match and added Demo trip descriptions

---

server/api/gatekeepingmiddleware.js

Gatekeeping Debugging

---

client/components/ActiveTrips.js
client/components/Carousel.js
client/components/CompletedTrips.js
client/components/SingleUser.js
client/redux/tripReducer.js
package-lock.json
package.json
public/index.css
public/index.html
seed.js
server/api/tripRoutes.js

cards can slide but I want to come back to them to fix them 
delete button, trip role, and dates all show up now when a user creates a trip!

Fix trip cards

---

client/components/Navbar.js

the drop down showed browse demos twice got rid of one

fixed the demos duplicate in dropwdown

---

client/components/TaskComponents/EditTaskModal.js
client/components/TaskComponents/TaskCard.js

Changed:
- rm edit task success msg
Added:
- success toast for edit task

Trip task toasts

---

client/components/ActiveTrips.js
client/components/CompletedTrips.js
client/components/InviteEmail.js
public/index.css
server/api/mail.js

fixed a bug that didnt let users send an email

 Center text

---

server/api/confirmationEmail.js
server/api/mail.js

added a port number to transporter

added port number to transporter

---

server/api/confirmationEmail.js
server/api/mail.js

changed from back to string with email and changed port number

changed port number and changed from prop in mailOptions

---

client/components/ActiveTrips.js
client/components/CompletedTrips.js
package-lock.json
package.json
public/index.css

fixed trip cards finally

---

client/components/TaskComponents/AddNewTaskModal.js
client/components/TaskComponents/EditTaskModal.js

Changed:
- added checks for duplicate errs in AddNewTask Modal and EditTaskModal
- added clear errs on modal x-button close

rm persistent form error alerts on modal xclose

---

server/api/gatekeepingmiddleware.js

middleware debug
